export const tables = {
  users: ['用户', 'OpenID、微信号、手机号和地址资料；使用同一用户 ID 关联行程和互动。'],
  rides: ['行程', '司机发布和乘客需求，包含出发时间、票面价格与余座。'],
  ride_members: ['行程成员', '用户在每条行程中的身份、座位数及加入状态。'],
  ride_stops: ['路线地点', '行程起终点与途经点，按路线顺序记录。'],
  ride_templates: ['每周模板', '固定星期、时间和路线的常用发布模板。'],
  ride_completions: ['成行回访', '首页与历史行程回访结果；关闭回访的推定成行与明确回答分开记录。'],
  ride_ratings: ['司机评分', '每次行程给司机的星级反馈。'],
  notifications: ['通知', '加入、退出与行程变动通知。'],
  user_blocks: ['屏蔽关系', '用户之间的屏蔽设置。'],
  referral_codes: ['邀请编号', '用户的邀请标识。'],
  referral_bindings: ['邀请关系', '邀请人与新用户的关联。'],
  city_requests: ['城市申请', '用户申请增加服务城市的记录。'],
  market_listings: ['二手与转租', '发布内容、联系人和状态；请使用社区管理进行版本编辑。'],
  market_views: ['社区浏览', '商品或房源的浏览记录。'],
  market_templates: ['发布模板', '管理员保存的二手与转租文字模板。'],
  market_import_batches: ['批量发布记录', '每批发布结果和原始请求编号，防止重复发布。'],
  community_configs: ['社区公告', '当前群二维码与公告；请在群码与公告页面修改。'],
  community_revisions: ['公告历史', '历次公告的版本记录。'],
  public_statistics: ['公开统计', '小程序展示的汇总数量。'],
  business_events: ['行程变动', '按行程版本保留的发布、加入和退出等业务事件。'],
  business_event_delivery: ['采集投递', '业务事件投递到采集服务的状态。'],
  files: ['图片资料', '文件编号、大小和状态，图片内容存放在对象存储。'],
  file_references: ['图片引用', '文件与头像、商品、公告的关联。'],
  ads: ['广告', '广告内容、展示条件及状态。'],
  ad_clicks: ['广告点击', '广告的点击记录。'],
  admin_accounts: ['管理员', '账号与权限；密码和凭证不在控制台展示。'],
  admin_audit: ['管理操作', '管理员执行变更的时间、目标与记录。'],
  admin_origins: ['管理站来源', '允许访问管理接口的网站地址。'],
  admin_requests: ['管理操作回执', '保存已确认操作的结果，防止网络重试产生重复变更。'],
  idempotency_requests: ['用户操作回执', '用户请求的去重结果。'],
  migration_batches: ['迁移批次', '保留切库时的批次核对信息。'],
  migration_sources: ['原始记录', '迁移来源和原始归档，只读保留。'],
}
export const fields = {
  id: ['记录 ID', '当前记录的唯一标识。'], key: ['记录定位', '控制台定位此记录的主键。'], app_id: ['小程序', '所属小程序的 AppID。'],
  openid: ['OpenID', '微信身份标识，用于关联同一用户的资料、行程和互动。'], user_id: ['用户 ID', '对应用户表的 ID。'], creator_id: ['发布者 ID', '发布行程的用户 ID。'], actor_id: ['操作者 ID', '触发此次事件的用户 ID。'], owner_user_id: ['用户所有者', '商品或文件所属用户 ID。'],
  name: ['显示名称', '用户当前显示的姓名或昵称。'], avatar_url: ['头像地址', '用户头像的地址。'], profile: ['个人资料', '微信号、手机号、常用地址等用户填写的资料。合并保存；清空可填写空字符串或空列表。'],
  created_at: ['创建时间', '此记录创建的时间。'], updated_at: ['更新时间', '最近一次修改的时间。'], version: ['版本', '修改时用于确认记录没有被其他人更新。'],
  ride_id: ['行程 ID', '对应行程表的 ID。'], trip_id: ['行程 ID', '对应的行程标识。'], kind: ['类型', '行程发布或乘客需求等记录类型。'], city_key: ['城市', '所属服务城市。'], status: ['状态', '当前有效、取消、关闭或删除状态。'], state: ['状态', '当前关系或服务的状态。'],
  seat_capacity: ['总座位', '行程允许的乘客座位数。'], seat_count: ['占用座位', '此成员申请的座位数。'], departure_at: ['出发时间', '计划出发的时间。'], time_zone: ['时区', '行程时间采用的时区。'], listed_price_cents: ['票面价格（美分）', '发布时每位乘客的价格，除以 100 得到美元。'],
  details: ['详细资料', '该记录的补充内容。'], content: ['发布内容', '标题、描述、价格、联系人和位置信息。'], payload: ['事件内容', '业务事件发生时的相关数据。'], data: ['采集内容', '页面曝光、点击、联系和回访等事件字段。'],
  role: ['身份', '司机、乘客或管理员权限。'], joined_at: ['加入时间', '成员加入行程的时间。'], left_at: ['退出时间', '成员退出的时间。'], position: ['顺序', '路线地点的排列次序。'], address: ['地点', '用户填写的上下车地点。'], place_id: ['地点 ID', '常用地点的稳定编号。'],
  rating: ['星级', '给司机的 1 至 5 星评价。'], stars: ['星级', '给司机的 1 至 5 星评价。'], rater_id: ['评分用户', '提交评分的用户 ID。'], driver_id: ['司机 ID', '被评价的司机用户 ID。'], outcome: ['成行结果', '明确回答或推定的成行结果。'], source: ['来源', '此数据的页面、操作或迁移来源。'],
  expires_at: ['到期时间', '记录有效期结束的时间。'], enabled: ['开启', '当前是否启用。'], read_at: ['已读时间', '通知被查看的时间。'], title: ['标题', '展示给用户的标题。'], body: ['正文', '通知或公告的正文。'], type: ['类型', '记录类型。'], target_id: ['目标 ID', '此操作针对的用户或内容。'], blocked_id: ['被屏蔽用户', '被屏蔽的用户 ID。'], blocker_id: ['屏蔽者', '设置屏蔽的用户 ID。'],
  account_id: ['管理员账号', '执行操作的管理员账号。'], admin_owner_key: ['管理归属', '发布此内容的管理账号归属。'], owner_key: ['归属编号', '管理账号的稳定归属标识。'], shared_admin_management: ['允许管理', '是否允许普通管理员管理这条用户发布内容。'], action: ['操作', '执行的操作名称。'], operation: ['操作名称', '请求对应的业务操作。'], request_key: ['操作编号', '网络重试时使用的原始操作编号。'], response_status: ['响应状态', '操作确认时的 HTTP 状态。'], response_body: ['操作结果', '已确认操作的结果。'],
  file_id: ['文件 ID', '对象存储文件的稳定编号。'], size_bytes: ['大小（字节）', '文件的数据大小。'], mime_type: ['文件类型', '图片或文件的格式。'], width: ['宽度', '图片宽度，单位为像素。'], height: ['高度', '图片高度，单位为像素。'], storage_key: ['存储位置', '文件的存储对象位置。'],
  batch_id: ['批次 ID', '一次批量发布或上传的编号。'], imported_at: ['导入时间', '此记录导入新数据库的时间。'], observed_at: ['观察时间', '原始数据被读取的时间。'], collection: ['原集合', '迁移之前的数据集合名称。'], document_id: ['原记录 ID', '迁移之前的记录标识。'], canonical_id: ['当前 ID', '迁移后的记录标识。'],
  receivedAt: ['接收时间', '服务器接收数据的时间；采集列表按此时间从新到旧。'], occurredAt: ['发生时间', '客户端记录的事件时间，可能受设备时钟影响。'], eventName: ['事件', '此次曝光、点击、联系或回访的事件名称。'], eventId: ['事件 ID', '用于去重的唯一事件编号。'], participantKey: ['采集标识', '关联同一用户采集记录的内部标识。'], batchId: ['上传批次', '一次合并上传的批次编号。'], schemaVersion: ['格式版本', '采集数据的字段格式版本。'], sessionId: ['访问会话', '关联同一次使用过程中的互动。'], context: ['页面环境', '事件发生时的页面和版本等信息。'],
  avatar_file_id: ['头像文件', '当前头像的稳定文件编号。'], credential_version: ['凭证版本', '变更密码或权限时递增，用于撤销原会话。'], phoneRegion: ['手机地区', '手机号对应的地区代码。'], wechatId: ['微信号', '用户填写的微信联系号。'], bio: ['个人简介', '用户主动填写的自我介绍。'], vehicle: ['车辆资料', '车牌、品牌和型号。'], plate: ['车牌', '司机填写的车牌信息。'], brand: ['品牌', '车辆品牌。'], model: ['型号', '车辆型号。'], zelle: ['收款资料', '用户填写的 Zelle 收款资料。'], account: ['收款账号', '用户填写的收款账号。'], public: ['公开显示', '是否允许向行程成员显示。'], preferences: ['常用设置', '常用上下车地址、备注和路线价格。'], pickupAddresses: ['常用上车点', '用户保存的上车地址。'], dropoffAddresses: ['常用下车点', '用户保存的下车地址。'], residence: ['住址', '用户填写的居住地点。'], latitude: ['纬度', '位置的纬度坐标。'], longitude: ['经度', '位置的经度坐标。'], priceCents: ['价格（美分）', '除以 100 得到美元。'], sellerContact: ['联系人', '发布者提供的姓名、微信号和电话。'], listingType: ['发布类型', '二手商品或房屋转租。'], startDate: ['开始日期', '取货或可入住的开始日期。'], endDate: ['结束日期', '取货或租期的结束日期。'],
  tripKey: ['行程 ID', '被看到、点击或回访的行程标识。'], tripType: ['行程类型', 'carpool 为司机发布，request 为乘客需求。'], selectionSetId: ['候选列表编号', '关联一次列表、其中的卡片曝光和点击。'], searchId: ['搜索编号', '关联搜索条件和展示结果。'], candidates: ['候选行程', '当时列表展示的行程和次序。'], candidatesComplete: ['完整候选', '此快照是否完整涵盖当时展示的候选列表。'], renderedCount: ['展示条数', '该列表当时绘制的行程数量。'], loadedDateCount: ['日期数量', '此次加载涵盖的日期数量。'], hasMore: ['仍有结果', '是否还有后续结果。'], availableSeats: ['可用座位', '互动时的剩余座位。'], serviceDate: ['出行日期', '筛选或行程对应的当地日期。'], departureMinute: ['出发分钟', '当地当日第几分钟，除以 60 得到小时。'], originArea: ['出发区域', '此次行程或搜索的出发区域。'], destinationArea: ['到达区域', '此次行程或搜索的到达区域。'], referencePriceCents: ['参考价格（美分）', '发布时的票面价，不代表用户实付金额。'], priceKind: ['价格来源', '司机票面价或需求参考价的类型。'], currency: ['币种', '该价格的货币。'], followupId: ['回访编号', '同一次成行回访的稳定标识。'], assumedOutcome: ['推定成行', '用户点关闭后按已有产品规则记录的推定结果，不等同明确回答。'], outcomeScope: ['结果范围', '司机表示至少一名乘客成行；乘客表示自己的预约是否成行。'], dismissalReason: ['关闭原因', '主动关闭与页面离开分开记录。'], visibilityBucket: ['曝光判定', '卡片达到可见比例和持续时间的条件。'], snapshotAt: ['快照时间', '客户端保存该行程快照的时间。'], tripVersion: ['行程版本', '互动时对应的行程版本。'], dataGeneratedAt: ['数据生成时间', '服务器生成当时列表数据的时间。'], dataTimeSource: ['时间来源', '数据生成时间是否由服务器提供。'], originPlaceIds: ['出发地点编号', '行程关联的出发公共地点。'], destinationPlaceIds: ['到达地点编号', '行程关联的到达公共地点。'], channel: ['联系渠道', '微信、电话或收款资料。'], targetRole: ['联系对象', '司机或乘客。'], partySize: ['同行人数', '搜索时需要的座位数量。'], intentId: ['需求编号', '关联同一次出行需求的不同搜索。'], hideFullTrips: ['隐藏满座', '搜索时是否隐藏已满行程。'], pickerSessionId: ['选点过程', '关联同一次地点选择过程。'], placeId: ['地点编号', '此次选中或展示的公共地点。'], mode: ['选点用途', '司机发布、乘客需求或列表筛选。'], field: ['地点位置', 'departure 为出发，destination 为到达。'], cityKey: ['服务城市', '地点或行程所属城市。'], catalogVersion: ['地点版本', '当前地点目录的版本。'], rankingVersion: ['排序版本', '推荐地点的排序规则版本。'], snapshotId: ['推荐编号', '此次地点推荐列表的快照。'], circleIds: ['常用区域', '依据往返记录推定的常用地区。'], cacheAgeMs: ['缓存时长', '使用的缓存距生成时间有多久，单位毫秒。'], clientVersion: ['小程序版本', '事件发生时的小程序版本。'], sdkVersion: ['基础库版本', '事件发生时使用的微信基础库。'], platform: ['设备平台', 'iOS、Android 或开发者工具。'], buildMode: ['版本类型', '开发版、体验版或正式版。'], page: ['页面', '用户看到的页面。'], durationMs: ['耗时（毫秒）', '操作从开始到结束的耗时。'],
  active: ['生效', '此设置或关系是否仍然生效。'], actor_user_id: ['操作用户', '执行此操作的用户 ID。'], ad_id: ['广告 ID', '对应广告记录。'],
  before_content: ['修改前内容', '操作之前保留的内容。'], after_content: ['修改后内容', '操作之后保存的内容。'],
  attempt_count: ['尝试次数', '当前限流时间窗口内的尝试次数。'], badge_text: ['角标文字', '广告卡片上的短标签。'], blocked_at: ['屏蔽时间', '屏蔽设置创建的时间。'], bound_at: ['关联时间', '邀请或账号关系建立的时间。'],
  city_aliases: ['城市别名', '同一城市的其他输入名称。'], city_label: ['城市名称', '展示给用户的城市名称。'], code: ['编号', '邀请等业务的稳定编号。'], count: ['数量', '对应范围内汇总的数量。'], total: ['总数', '对应范围内累计的数量。'], counted_at: ['统计时间', '此汇总数据生成的时间。'],
  created_by_admin_id: ['创建管理员', '创建此内容的管理员账号。'], updated_by_admin_id: ['更新管理员', '最近修改此内容的管理员账号。'], uploaded_by_admin_id: ['上传管理员', '上传此图片的管理员账号。'], cta_text: ['操作文字', '广告按钮的显示文字。'],
  day: ['日期', '统计或记录所属的日期。'], weekday: ['星期', '每周模板重复执行的星期。'], local_time: ['本地时间', '每周模板中的出发时刻。'], definition: ['定义', '模板或统计的具体设置。'],
  document_json: ['原始内容', '切库时保留的来源记录，只读归档。'], start_at: ['开始时间', '内容开始展示或生效的时间。'], end_at: ['结束时间', '内容停止展示或生效的时间。'], event_id: ['事件 ID', '业务或采集事件的唯一编号。'],
  failures: ['失败记录', '该批次中明确失败的条目。'], results: ['发布结果', '该批次中已确认发布的条目。'], last_seen_at: ['最近使用', '此会话最近被使用的时间。'], legacy_readonly: ['历史只读', '迁移来的图片只能保留引用，不开放修改。'],
  listing_id: ['发布 ID', '对应商品或房源的 ID。'], listing_type: ['发布类型', '二手商品或房屋转租。'], locator: ['文件位置', '对象存储内的文件定位信息。'], media_type: ['媒体类型', '文件的 MIME 格式。'], origin: ['网站来源', '获准调用管理接口的网站 origin。'],
  payload_format: ['请求格式', '保存请求时采用的数据格式。'], payload_hash: ['内容摘要', '验证重试请求与原始内容是否一致。'], placement: ['展示位置', '广告在小程序中的展示位置。'], previous_version: ['上一版本', '变更之前的内容版本。'],
  priority: ['优先级', '内容展示或处理顺序。'], provider: ['存储服务', '此文件使用的存储服务。'], rater_role: ['评分身份', '评分者在该行程中的身份。'], target_role: ['被评身份', '被评价的人在该行程中的身份。'], read: ['已读', '通知是否已经查看。'], reason: ['原因', '此结果或操作的说明。'],
  referred_user_id: ['被邀请用户', '通过邀请加入的用户 ID。'], referrer_user_id: ['邀请人', '发出邀请的用户 ID。'], resource_id: ['资源 ID', '该记录关联的内容或文件 ID。'], resource_kind: ['资源类型', '头像、商品、公告等关联类型。'],
  ride_version: ['行程版本', '此事件对应的行程版本。'], scope: ['范围', '操作、限流或统计针对的范围。'], score: ['评分', '用户提交的司机星级。'], served_count: ['展示次数', '此内容已经展示的次数。'], slot: ['展示栏位', '广告或内容的展示栏位。'],
  source_id: ['来源 ID', '迁移之前的记录编号。'], source_page: ['来源页面', '用户互动所在的页面。'], subtitle: ['副标题', '内容的补充说明文字。'], target: ['目标', '此内容的跳转或操作目标。'], verified_at: ['核验时间', '身份或内容被核验的时间。'], weight: ['权重', '排序时使用的相对权重。'], window_start: ['窗口开始', '此统计或限流时间窗口的起点。'],
  listed_price_label: ['价格文字', '发布时保留的价格显示文字。'], collector_payload: ['投递内容', '等待发送到采集服务的业务数据。'], collector_delivered_at: ['投递时间', '采集服务确认接收此业务数据的时间。'], coverage_text: ['统计范围', '公开汇总涵盖的数据范围说明。'], upload_request_key: ['上传操作编号', '重复上传核对使用的原始编号。'], plan_sha256: ['迁移计划摘要', '核对迁移计划一致性的摘要。'], imported_counts: ['导入数量', '各类迁移记录的核对数量。'], observed_before: ['观察界限', '迁移观察记录覆盖的时间界限。'],
  phone: ['手机号', '用户主动填写的联系电话。'], wechat: ['微信号', '用户主动填写的微信联系号。'], pickup: ['上车地点', '此路线记忆或当次填写的上车地点。'], dropoff: ['下车地点', '此路线记忆或当次填写的下车地点。'],
}
export function tableInfo(key) { const value = tables[key]; return { label: value?.[0] || key, description: value?.[1] || '业务数据表。字段类型来自当前数据库。' } }
export function fieldInfo(key, type = '') { const value = fields[key]; return { label: value?.[0] || key, description: value?.[1] || `此记录的 ${key} 字段${type ? `（${type}）` : ''}。` } }
export function formatValue(value) { if (value === null || value === undefined) return '—'; if (typeof value === 'object') return JSON.stringify(value); if (typeof value === 'boolean') return value ? '是' : '否'; return String(value) }
export const isSuperadmin = session => session?.admin?.role === 'superadmin'

const eventLabels = { page_view: '页面浏览', search_submitted: '搜索', result_set_rendered: '候选列表', list_snapshot: '候选快照', result_card_visible: '卡片曝光', trip_card_clicked: '行程点击', trip_detail_opened: '打开详情', detail_viewed: '详情浏览', contact_entry_clicked: '联系入口', contact_action: '联系操作', followup_presented: '显示回访', followup_dismissed: '关闭回访', followup_answer: '回答回访', place_picker_open: '打开地点选择', place_picker_rendered: '地点推荐展示', place_picker_selected: '选择地点', place_picker_dismissed: '关闭地点选择', place_picker_custom: '自定义地点', referral_visit: '邀请访问', no_suitable_option: '没有合适行程', service_request: '服务请求', client_error: '历史错误记录', collection_diagnostic: '历史采集诊断' }
export const eventLabel = name => eventLabels[name] || name
