import React, { useEffect, useRef, useState } from 'react'
import { Field, Notice } from './App.jsx'
import { CopyID, StructuredValue } from './DataBrowser.jsx'
import { fieldInfo, eventLabel } from './catalog.js'
import { time } from './Monitor.jsx'
export default function CollectionLog({ api }) {
  const [query, setQuery] = useState({ openid: '', from: '', to: '' }), [filter, setFilter] = useState({}), [type, setType] = useState(''), [result, setResult] = useState(null), [selected, setSelected] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const generation = useRef(0)
  async function load(cursor = null) { const epoch = ++generation.current; setBusy(true); setError(''); try { const value = await api.call('consoleEvents', { ...filter, cursor }); if (epoch === generation.current) setResult(value) } catch (error) { if (epoch === generation.current) setError(error.message) } finally { if (epoch === generation.current) setBusy(false) } }
  useEffect(() => { setResult(null); setSelected(null); void load(); return () => { generation.current++ } }, [api, filter])
  function submit(event) { event.preventDefault(); const from = query.from ? new Date(query.from).getTime() : undefined, to = query.to ? new Date(query.to).getTime() : undefined; if ((from !== undefined && !Number.isFinite(from)) || (to !== undefined && !Number.isFinite(to)) || (from !== undefined && to !== undefined && from >= to)) { setError('请检查开始和结束时间'); return }; setFilter({ openid: query.openid.trim() || undefined, from, to }); setType('') }
  const events = result?.events || [], visible = type ? events.filter(event => event.eventName === type) : events
  return <>
    <div className="page-heading"><div><div className="eyebrow">最高管理员</div><h1>采集记录</h1><p>按服务器接收时间从新到旧显示；按需读取，不持续扫描数据库。</p></div><button className="button secondary" disabled={busy} onClick={() => load()}>刷新</button></div>
    <Notice message={error} />
    <section className="panel"><form className="console-toolbar collection-filter" onSubmit={submit}><Field label="OpenID / 用户 ID"><input value={query.openid} maxLength={160} onChange={event => setQuery(old => ({ ...old, openid: event.target.value }))} placeholder="留空查看全部用户" /></Field><Field label="接收开始时间"><input type="datetime-local" value={query.from} onChange={event => setQuery(old => ({ ...old, from: event.target.value }))} /></Field><Field label="接收结束时间"><input type="datetime-local" value={query.to} onChange={event => setQuery(old => ({ ...old, to: event.target.value }))} /></Field><button className="button primary" disabled={busy}>查询</button></form><div className="sample-line"><span>查询时间 {time(result?.sampledAt)}</span><label className="inline-filter">本页事件 <select value={type} onChange={event => setType(event.target.value)}><option value="">全部</option>{[...new Set(events.map(event => event.eventName))].map(name => <option value={name} key={name}>{eventLabel(name)} · {name}</option>)}</select></label></div><div className="table-scroll"><table className="data-table"><thead><tr><th>接收时间</th><th>事件</th><th>OpenID</th><th>发生时间</th><th>详情</th></tr></thead><tbody>{visible.map(event => <tr key={`${event.batchId}:${event.eventId}`}><td>{time(event.receivedAt)}</td><td><strong title={event.eventName}>{eventLabel(event.eventName)}</strong><code className="record-id">{event.eventName}</code><code className="record-id">{event.eventId}</code></td><td>{event.openid ? <CopyID value={event.openid} /> : '—'}</td><td>{time(event.occurredAt)}</td><td><button className="text-button" onClick={() => setSelected(event)}>查看</button></td></tr>)}</tbody></table></div>{!visible.length && <p className="empty-list">{busy ? '正在读取…' : '此页没有对应事件'}</p>}<div className="page-actions"><span className="muted">本页显示 {visible.length} 条 · 已检查 {result?.scanned ?? 0} 条事件索引</span>{result?.nextCursor && <button className="button secondary" disabled={busy} onClick={() => load(result.nextCursor)}>下一页</button>}</div></section>
    {selected && <section className="panel collection-detail"><div className="panel-heading"><h2>采集详情 · {eventLabel(selected.eventName)}</h2><button className="text-button" onClick={() => setSelected(null)}>收起</button></div><dl className="row-detail">{Object.entries(selected).map(([field, value]) => <div key={field}><dt>{fieldInfo(field).label}<code>{field}</code><small>{fieldInfo(field).description}</small></dt><dd>{typeof value === 'object' && value !== null ? <StructuredValue value={value} /> : <span>{String(value ?? '—')}</span>}</dd></div>)}</dl></section>}
  </>
}
