import React, { useEffect, useRef, useState } from 'react'
import { ConfirmDialog, Field, Notice } from './App.jsx'
import { time } from './Monitor.jsx'
import { formatValue, isSuperadmin } from './catalog.js'
export default function CommunityListings({ api }) {
  const [items, setItems] = useState([]), [cursor, setCursor] = useState(null), [status, setStatus] = useState('all'), [selected, setSelected] = useState([]), [busy, setBusy] = useState(false), [error, setError] = useState(''), [confirm, setConfirm] = useState(false), [edit, setEdit] = useState(null), [content, setContent] = useState(''), [success, setSuccess] = useState('')
  const generation = useRef(0), superadmin = isSuperadmin(api.getSession())
  async function load(next = null) { const epoch = ++generation.current; setBusy(true); setError(''); try { const result = await api.call('listItems', { status, cursor: next }); if (epoch !== generation.current) return; setItems(old => next ? [...old, ...result.items] : result.items); setCursor(result.nextCursor); if (!next) setSelected([]) } catch (error) { if (epoch === generation.current) setError(error.message) } finally { if (epoch === generation.current) setBusy(false) } }
  useEffect(() => { void load(); return () => { generation.current++ } }, [status, api])
  function toggle(id) { setSelected(old => old.includes(id) ? old.filter(value => value !== id) : old.length < 50 ? [...old, id] : old) }
  async function remove() { setBusy(true); setError(''); try { const result = await api.call('deleteItems', { items: items.filter(item => selected.includes(item.id)).map(item => ({ id: item.id, expectedVersion: item.version })) }); setItems(old => old.filter(item => !result.deleted.some(row => row.id === item.id))); setSelected([]); setSuccess(`已删除 ${result.deleted.length} 条内容`); setConfirm(false) } catch (error) { setError(error.message); setConfirm(false) } finally { setBusy(false) } }
  async function beginEdit(item) { setBusy(true); setError(''); try { const value = await api.call('getItem', { id: item.id }); setEdit(value); setContent(JSON.stringify(value.content, null, 2)) } catch (error) { setError(error.message) } finally { setBusy(false) } }
  async function save() { setBusy(true); setError(''); try { const patch = JSON.parse(content); if (!patch || Array.isArray(patch) || typeof patch !== 'object' || 'images' in patch) throw Error('请填写有效内容；图片保持原引用'); await api.call('updateItem', { id: edit.id, expectedVersion: edit.version, patch }); setEdit(null); setSuccess('已保存商品内容'); await load() } catch (error) { setError(error.message) } finally { setBusy(false) } }
  async function changeStatus(item, value) { setBusy(true); setError(''); try { await api.call('itemStatus', { id: item.id, expectedVersion: item.version, status: value }); await load(); setSuccess('已更新状态') } catch (error) { setError(error.message) } finally { setBusy(false) } }
  return <>
    <div className="page-heading"><div><div className="eyebrow">社区管理</div><h1>已发布内容</h1><p>查看二手商品与转租内容，批量移除无效发布。</p></div><button className="button secondary" onClick={() => load()} disabled={busy}>刷新</button></div>
    <Notice message={error} /><Notice message={success} kind="success" />
    <section className="panel"><div className="console-toolbar"><Field label="状态"><select value={status} onChange={event => setStatus(event.target.value)} disabled={busy}>{[['all', '全部'], ['online', '展示中'], ['offline', '已下架'], ['sold', '已成交']].map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></Field><div className="button-row"><span className="muted">已选 {selected.length} / 50 条</span><button className="button danger-button" disabled={busy || !selected.length} onClick={() => setConfirm(true)}>批量删除</button></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th><input type="checkbox" aria-label="选择当前前 50 条" checked={!!items.length && selected.length === Math.min(50, items.length)} onChange={event => setSelected(event.target.checked ? items.slice(0, 50).map(item => item.id) : [])} disabled={busy} /></th><th>标题 / ID</th><th>类型</th><th>状态</th><th>发布时间</th>{superadmin && <th>管理</th>}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td><input type="checkbox" aria-label={`选择 ${item.content?.title || item.id}`} checked={selected.includes(item.id)} onChange={() => toggle(item.id)} disabled={busy} /></td><td><strong>{item.content?.title || item.title || '未命名'}</strong><code className="record-id">{item.id}</code></td><td>{(item.content?.listingType || item.listingType) === 'sublet' ? '转租' : '二手'}</td><td>{formatValue(item.status)}</td><td>{time(item.createdAt || item.created_at)}</td>{superadmin && <td><div className="button-row"><button className="text-button" disabled={busy} onClick={() => beginEdit(item)}>编辑</button><select aria-label={`修改 ${item.id} 状态`} value={item.status} disabled={busy} onChange={event => changeStatus(item, event.target.value)}><option value="online">展示中</option><option value="offline">下架</option><option value="sold">成交</option></select></div></td>}</tr>)}</tbody></table></div>{!items.length && <p className="empty-list">{busy ? '正在读取…' : '没有对应内容'}</p>}<div className="page-actions"><span className="muted">已显示 {items.length} 条</span>{cursor && <button className="button secondary" disabled={busy} onClick={() => load(cursor)}>继续加载</button>}</div></section>
    {confirm && <ConfirmDialog title={`删除 ${selected.length} 条社区内容？`} confirmText="确认删除" busy={busy} onConfirm={remove} onClose={() => setConfirm(false)}><p>选中的商品和房源会立即从小程序和公开网站中移除。</p><p className="field-hint">服务器保留删除记录。重复核对同一操作不会再次删除其他内容。</p></ConfirmDialog>}
    {edit && <ConfirmDialog title="编辑发布内容" confirmText="保存修改" busy={busy} onConfirm={save} onClose={() => setEdit(null)}><Notice message={error} /><Field label="内容" hint="价格 priceCents 以美分计；联系人 sellerContact，地区 region，日期 startDate/endDate。原有图片保持不变。"><textarea className="json-editor" rows={18} value={content} onChange={event => setContent(event.target.value)} spellCheck={false} /></Field></ConfirmDialog>}
  </>
}
