import React, { useEffect, useRef, useState } from 'react'
import { Field, Notice } from './App.jsx'
import { fieldInfo, formatValue, tableInfo } from './catalog.js'
export function CopyID({ value }) { const [copied, setCopied] = useState(false); useEffect(() => { if (!copied) return; const timer = setTimeout(() => setCopied(false), 1500); return () => clearTimeout(timer) }, [copied]); return <button className="text-button copy-id" title={value} onClick={async () => { try { await navigator.clipboard.writeText(value); setCopied(true) } catch (_) { setCopied(false) } }}>{copied ? '已复制' : value}</button> }
export default function DataBrowser({ api, onNavigate }) {
  const [tables, setTables] = useState([]), [table, setTable] = useState('users'), [query, setQuery] = useState(''), [search, setSearch] = useState(''), [result, setResult] = useState(null), [detail, setDetail] = useState(null), [editing, setEditing] = useState(false), [draft, setDraft] = useState({}), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const generation = useRef(0), current = tables.find(item => item.key === table)
  useEffect(() => { let active = true; api.call('consoleTables').then(result => { if (active) setTables(result.tables) }).catch(error => { if (active) setError(error.message) }); return () => { active = false } }, [api])
  async function load(cursor = null) { const epoch = ++generation.current; setBusy(true); setError(''); try { const result = await api.call('consoleRows', { table, search, cursor }); if (epoch === generation.current) setResult(result) } catch (error) { if (epoch === generation.current) setError(error.message) } finally { if (epoch === generation.current) setBusy(false) } }
  useEffect(() => { setResult(null); setDetail(null); void load(); return () => { generation.current++ } }, [api, table, search])
  async function open(item) { const epoch = ++generation.current; setBusy(true); setError(''); setSuccess(''); try { const value = await api.call('consoleRow', { table, key: item.key }); if (epoch === generation.current) { setDetail(value); setEditing(false); setDraft(Object.fromEntries(value.editableFields.map(field => [field, typeof value.row[field] === 'object' ? JSON.stringify(value.row[field], null, 2) : formatValue(value.row[field]) ]))) } } catch (error) { if (epoch === generation.current) setError(error.message) } finally { if (epoch === generation.current) setBusy(false) } }
  async function save() { setBusy(true); setError(''); try { const patch = {}; for (const field of detail.editableFields) { const type = current.columns.find(column => column.name === field)?.type || ''; const value = type.includes('json') ? JSON.parse(draft[field]) : draft[field]; if (JSON.stringify(value) !== JSON.stringify(detail.row[field])) patch[field] = value }; if (!Object.keys(patch).length) { setEditing(false); return }; const value = await api.call('consoleEdit', { table, key: detail.key, expectedVersion: detail.version, patch }); setDetail({ ...detail, ...value }); setEditing(false); setSuccess('已保存修改'); await load() } catch (error) { setError(error.message) } finally { setBusy(false) } }
  const columns = current?.columns || [], visible = columns.slice(0, 6)
  return <>
    <div className="page-heading"><div><div className="eyebrow">最高管理员</div><h1>数据浏览</h1><p>按用户或记录 ID 查看关联资料。每次读取一页，按需刷新。</p></div><button className="button secondary" disabled={busy} onClick={() => load()}>刷新</button></div>
    <Notice message={error} /><Notice message={success} kind="success" />
    <section className="panel"><form className="console-toolbar" onSubmit={event => { event.preventDefault(); if (search === query.trim()) void load(); else setSearch(query.trim()) }}><Field label="数据表"><select value={table} onChange={event => setTable(event.target.value)} disabled={busy || !tables.length}>{tables.map(item => <option value={item.key} key={item.key}>{tableInfo(item.key).label} · {item.key}</option>)}</select></Field><Field label="ID / OpenID" hint="精确查询记录 ID，或查询该用户关联的记录。"><input value={query} onChange={event => setQuery(event.target.value)} maxLength={160} placeholder="留空查看所有记录" /></Field><button className="button primary" disabled={busy}>查询</button></form><div className="catalog-note"><strong>{tableInfo(table).label}</strong><span>{tableInfo(table).description}</span><span className="status-pill">{current?.editableFields?.length ? '支持受控编辑' : '只读'}</span></div><div className="table-scroll"><table className="data-table"><thead><tr>{visible.map(column => <th key={column.name} title={fieldInfo(column.name, column.type).description}>{fieldInfo(column.name).label}<small>{column.name}</small></th>)}<th>操作</th></tr></thead><tbody>{(result?.items || []).map(item => <tr key={item.key}>{visible.map(column => <td key={column.name} title={formatValue(item.row[column.name])}><span className="truncated-value">{formatValue(item.row[column.name])}</span></td>)}<td><button className="text-button" disabled={busy} onClick={() => open(item)}>查看完整资料</button></td></tr>)}</tbody></table></div>{!result?.items?.length && <p className="empty-list">{busy ? '正在读取…' : '没有找到对应记录'}</p>}<div className="page-actions"><span className="muted">本页 {result?.items?.length || 0} 条{search ? ' · 已按 ID 筛选' : ''}</span>{result?.nextCursor && <button className="button secondary" disabled={busy} onClick={() => load(result.nextCursor)}>下一页</button>}</div></section>
    <details className="panel field-dictionary"><summary>字段说明</summary><dl>{columns.map(column => <div key={column.name}><dt>{fieldInfo(column.name).label}<code>{column.name}</code></dt><dd>{fieldInfo(column.name, column.type).description}<small>{column.type}{column.nullable ? ' · 可留空' : ''}{current.primaryKey.includes(column.name) ? ' · 主键' : ''}{current.editableFields.includes(column.name) ? ' · 可编辑' : ' · 只读'}</small></dd></div>)}</dl></details>
    {detail && <RowDialog title={tableInfo(table).label} onClose={() => { setDetail(null); setEditing(false) }} busy={busy}><Notice message={error} /><Notice message={success} kind="success" />{editing ? <><div className="edit-fields">{detail.editableFields.map(field => <Field key={field} label={`${fieldInfo(field).label} · ${field}`} hint={fieldInfo(field).description}>{typeof detail.row[field] === 'object' ? <textarea className="json-editor" rows={12} spellCheck={false} value={draft[field]} onChange={event => setDraft(old => ({ ...old, [field]: event.target.value }))} /> : <input value={draft[field]} onChange={event => setDraft(old => ({ ...old, [field]: event.target.value }))} />}</Field>)}</div><div className="button-row end"><button className="button secondary" disabled={busy} onClick={() => setEditing(false)}>取消编辑</button><button className="button primary" disabled={busy} onClick={save}>{busy ? '保存中…' : '保存修改'}</button></div></> : <><dl className="row-detail">{Object.entries(detail.row).map(([field, value]) => <div key={field}><dt>{fieldInfo(field).label}<code>{field}</code><small>{fieldInfo(field, columns.find(column => column.name === field)?.type).description}</small></dt><dd>{typeof value === 'object' && value !== null ? <StructuredValue value={value} /> : ['id', 'openid', 'user_id', 'creator_id', 'ride_id'].includes(field) && value ? <CopyID value={String(value)} /> : <span>{formatValue(value)}</span>}</dd></div>)}</dl><div className="button-row end">{detail.editableFields.length > 0 && <button className="button primary" onClick={() => setEditing(true)} disabled={busy}>编辑允许的字段</button>}{table === 'market_listings' && <button className="button secondary" onClick={() => onNavigate('listings')}>进入社区管理</button>}{['community_configs', 'community_revisions'].includes(table) && <button className="button secondary" onClick={() => onNavigate('community')}>进入群码与公告</button>}</div></>}</RowDialog>}
  </>
}
function RowDialog({ title, onClose, busy, children }) { const ref = useRef(null); useEffect(() => { ref.current.showModal() }, []); return <dialog className="data-dialog" ref={ref} onCancel={event => { event.preventDefault(); if (!busy) onClose() }}><div className="panel-heading"><h2>{title} · 完整记录</h2><button className="button secondary" onClick={onClose} disabled={busy}>关闭</button></div>{children}</dialog> }

export function StructuredValue({ value }) { return <><pre>{JSON.stringify(value, null, 2)}</pre>{!Array.isArray(value) && <details className="json-dictionary"><summary>内容字段说明</summary><dl>{Object.keys(value).map(field => <div key={field}><dt>{fieldInfo(field).label}<code>{field}</code></dt><dd>{fieldInfo(field).description}</dd></div>)}</dl></details>}</> }
