const errors = {
  CONSOLE_INVALID_KEY: '记录或分页已失效，请重新查询', CONSOLE_RESULT_TOO_LARGE: '内容过大，请缩小查询或单独查看记录', CONSOLE_TABLE_NOT_FOUND: '请选择有效的数据表', CONSOLE_BUSY: '控制台查询较多，请稍后刷新', CONSOLE_USER_NOT_FOUND: '请输入有效的用户 ID 或 OpenID', ADMIN_MONITOR_UNAVAILABLE: '运行监控或采集查询暂不可用，请稍后刷新', CONSOLE_ROW_READ_ONLY: '此表只读，请使用对应运营功能', CONSOLE_FIELD_READ_ONLY: '此字段不可修改',
  ADMIN_FORBIDDEN: '当前账号没有此操作权限', CONSOLE_VERSION_CONFLICT: '资料已更新，请重新加载后编辑', CONSOLE_TABLE_NOT_ALLOWED: '此表不开放控制台访问', CONSOLE_ROW_NOT_FOUND: '没有找到此记录', CONSOLE_UNAVAILABLE: '控制台暂不可用，请稍后刷新',
  INVALID_DATE_WINDOW: '请检查日期范围：商品最多两个月，转租最多十八个月',
  FILE_UPLOADER_MISMATCH: '请使用当前账号重新上传图片', FILE_READONLY: '历史图片只允许保留原引用，请重新上传',
  INVALID_CREDENTIALS: '账号或密码不正确', LISTING_NOT_FOUND: '商品不存在或不可管理',
  LISTING_VERSION_CONFLICT: '商品已更新，请重新加载后再编辑', FILE_OWNER_MISMATCH: '图片不可用于当前内容，请重新上传',
  FILE_NOT_READY: '图片尚未完成处理，请稍后重试原操作', INVALID_IMAGE: '图片无效，请选择 JPG、PNG 或 WebP 图片',
  FILE_STORAGE_UNAVAILABLE: '图片服务暂不可用，请稍后重试原操作', UPLOAD_CONTENT_CONFLICT: '相同图片操作编号的内容不一致，请核对原图',
  SERVICE_UNAVAILABLE: '服务暂时不可用，请稍后重试原操作',

  ADMIN_SESSION_INVALID: '登录已过期，请重新登录', ADMIN_UNAUTHORIZED: '登录已过期，请重新登录',
  ADMIN_INVALID_CREDENTIALS: '账号或密码不正确', ADMIN_LOGIN_RATE_LIMITED: '登录尝试次数较多，请稍后重试',
  ADMIN_ORIGIN_NOT_ALLOWED: '此网站地址尚未获得管理接口授权', ADMIN_CORS_NOT_ALLOWED: '此网站的请求方式尚未获得授权',
  BUSINESS_STAGED: '服务器尚未开放管理功能，请等待迁移完成', BACKEND_STAGED: '服务器尚未开放管理功能，请等待迁移完成',
  VALIDATION_ERROR: '请检查必填内容、日期和图片', INVALID_INPUT: '请检查填写内容',
  COMMUNITY_VERSION_CONFLICT: '群码或公告已更新，请重新加载后再保存', COMMUNITY_EXPIRED: '启用内容已过期，请更新有效期',
  MARKET_VERSION_CONFLICT: '商品已更新，请重新加载后再编辑', MARKET_LISTING_NOT_FOUND: '商品不存在或不可管理',
  IDEMPOTENCY_CONFLICT: '此操作内容与原请求不同，请先核对上次结果', LEGACY_REQUEST_CONFLICT: '这是旧版发布记录，请先核对原商品，不能直接再次发布',
  MARKET_BATCH_CONFLICT: '本批次内容与原请求不同，请保留原批次重试', FILE_NOT_FOUND: '图片不存在或不可访问，请重新上传',
  FILE_NOT_ALLOWED: '图片不可用于当前内容，请重新上传', FILE_UPLOAD_BUSY: '图片服务繁忙，请稍后重试原图片',
  FILE_TOO_LARGE: '图片超过 2 MB，请换一张较小的图片', FILE_INVALID_IMAGE: '图片无效，请选择 JPG、PNG 或 WebP 图片',
  FILE_PIXELS_EXCEEDED: '图片分辨率过大，请选择较小的图片',

  authentication_required: '登录已过期，请重新登录；未提交的内容仍保留在本页',
  session_invalid: '登录已过期，请重新登录；未提交的内容仍保留在本页',
  login_rate_limited: '登录尝试次数较多，请 15 分钟后再试',
  idempotency_conflict: '此条内容与原发布请求不一致，请核对已发布记录后再编辑',
  image_not_allowed: '此图片尚未获得使用授权，请重新选择并上传',
  invalid_community_config: '请检查群码有效期、公告内容和展示次数',
  service_unavailable: '服务暂时不可用，请稍后重试',
  item_save_failed: '保存结果尚未确认，请重试原批次以确认结果',
  missing_template_contact: '保存模板前请填写联系人和联系方式',
  missing_template_region: '保存模板前请选择城市、区域和细分区域',
  invalid_credentials: '账号或密码不正确', invalid_password: '账号或密码不正确',
  login_failed: '账号或密码不正确', too_many_attempts: '尝试次数较多，请稍后再登录',
  rate_limited: '操作过于频繁，请稍后再试', unauthorized: '登录已过期，请重新登录',
  session_expired: '登录已过期，请重新登录', forbidden: '当前账号没有此操作权限',
  invalid_origin: '此网站地址尚未获得管理接口授权', origin_not_allowed: '此网站地址尚未获得授权',
  not_configured: '管理后台尚未完成配置', conflict: '配置已被其他人更新，请重新加载后再保存',
  version_conflict: '配置已被其他人更新，请重新加载后再保存', missing_required_fields: '请补全必填项目',
  invalid_image: '图片格式无效，请选择 JPG、PNG 或 WebP 图片', image_too_large: '图片超过 2 MB，请换一张较小的图片',
  EXCEED_MAX_PAYLOAD_SIZE: '上传内容超过接口大小限制，请刷新后台后重试或选择较小的图片',
  invalid_file: '图片文件无效，请重新上传', file_not_owned: '这张图片不能用于当前发布，请重新上传',
  batch_conflict: '此批次内容已变化，请重新整理后发布', request_conflict: '这条发布内容已变化，请重新保存草稿',
  not_found: '记录不存在或已被移除', invalid_price: '请输入有效价格', invalid_dates: '请检查日期范围',
  invalid_pickup_range: '请检查开始和结束日期', invalid_expiry: '请填写将来的二维码到期时间'
}
export const errorMessage = code => errors[code] || '操作未完成，请稍后重试'
